# Generated by Django 4.1.5 on 2023-01-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('img', models.FileField(upload_to='upload')),
                ('description', models.CharField(max_length=10000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('img', models.FileField(upload_to='upload')),
                ('description', models.CharField(max_length=10000)),
                ('address', models.CharField(max_length=500)),
                ('menu', models.CharField(blank=True, max_length=500)),
                ('video', models.CharField(blank=True, max_length=500)),
                ('rating', models.IntegerField(max_length=1)),
                ('open', models.IntegerField(max_length=2)),
                ('close', models.IntegerField(max_length=2)),
                ('category', models.CharField(choices=[('c', 'Кафе'), ('r', 'Ресторан')], default='с', max_length=1)),
            ],
        ),
    ]
