# Generated by Django 4.1.5 on 2023-02-15 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_show_alter_event_date_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showphoto',
            name='photo',
            field=models.ImageField(upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='showphoto',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.food'),
        ),
        migrations.DeleteModel(
            name='Show',
        ),
    ]
