# Generated by Django 4.1.5 on 2023-02-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_showphoto_photo_alter_showphoto_show_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShowPhoto',
            new_name='FoodGalery',
        ),
    ]
