# Generated by Django 4.1.5 on 2023-02-15 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_food_galery_delete_foodgalery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='galery',
        ),
        migrations.CreateModel(
            name='FoodGalery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='upload')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.food')),
            ],
        ),
    ]
