# Generated by Django 4.1.5 on 2023-04-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_food_galery_foodgalery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgalery',
            name='photo',
            field=models.ImageField(upload_to='static/upload'),
        ),
    ]
