# Generated by Django 4.1.5 on 2023-04-20 14:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_foodgalery_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('img', models.FileField(upload_to='static/upload')),
                ('description', models.TextField(max_length=10000)),
                ('address', models.CharField(max_length=500)),
                ('menu', models.CharField(blank=True, max_length=500)),
                ('video', models.CharField(blank=True, max_length=500)),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('open', models.IntegerField(default=9, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)])),
                ('close', models.IntegerField(default=18, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('f', 'Пешком'), ('b', 'Вело'), ('a', 'Авто')], default='f', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.FileField(upload_to='static/upload'),
        ),
        migrations.AlterField(
            model_name='food',
            name='img',
            field=models.FileField(upload_to='static/upload'),
        ),
        migrations.CreateModel(
            name='PointGalery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/upload')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointphotos', to='api.food')),
            ],
        ),
    ]
