# Generated by Django 4.1.5 on 2023-04-21 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_point_alter_event_img_alter_food_img_pointgalery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointgalery',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointphotos', to='api.point'),
        ),
    ]
