# Generated by Django 4.1.5 on 2023-05-15 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_pointgalery_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='close',
            new_name='closeHour',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='open',
            new_name='openHour',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='close',
            new_name='closeHour',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='open',
            new_name='openHour',
        ),
        migrations.AlterField(
            model_name='point',
            name='category',
            field=models.CharField(choices=[('f', 'Пешком'), ('a', 'Авто'), ('b', 'Вело'), ('g', 'Гид')], default='f', max_length=1),
        ),
        migrations.AlterField(
            model_name='pointgalery',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.point'),
        ),
    ]
