# Generated by Django 4.1.5 on 2023-05-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_close_food_closehour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='menu',
            field=models.FileField(upload_to='static/upload'),
        ),
    ]
