# Generated by Django 4.1.5 on 2023-05-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_food_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='phone',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
